### ISSUE TITLE
Re-clustering of LSCs.

### ISSUE THREAD

**Issue by lconan** [andygxzeng/AMLHierarchies#3]
Hi, Andy.
I'm really interested in Re-clustering of LSCs.
I did run the code , but I haven't got clue on how 'HSC_Cycle_Primed', 'TNFA_via_NFKB', 'MYC_Targets_V1' are generated.
wonder if it's about the preprocessing step that I use scanpy for preprocessing.
Thanks, if you can help me to figure it out.

**Comment by andygxzeng** [comment]
Hi there - great catch and sorry that this was not in the github repo. 

These are geneset enrichment values scored by AUCell, running `sc.tl.score_genes` from scanpy or `AddModuleScore` from seurat will give similar results. I have added a custom script to perform geneset scoring with AUCell here: 
https://github.com/andygxzeng/AMLHierarchies/blob/main/AUCell_Geneset_Scoring.R

Here is a link to the gmt file containing the HSC_Cycle_Primed geneset (originally described in Xie et al Cell Stem Cell 2019 and Garcia Prat et al Cell Stem Cell 2021) 
https://github.com/andygxzeng/AMLHierarchies/blob/main/Data/Fig1_SingleCell_LSC/HSC_CyclePrimed_LSC_genesets.gmt

and a link to a gmt file containing the hallmark genesets from MSigDB including TNFA_via_NFKB and MYC_Targets_V1
https://github.com/andygxzeng/AMLHierarchies/blob/main/Data/Fig1_SingleCell_LSC/h.all.v7.0.symbols.gmt

You can find the fully processed scanpy object here to check for consistency: 
https://amlhierarchies.s3.us-east-2.amazonaws.com/scRNA_analysis/scAML_LSPC_scran_reclustered.h5ad

Hope that helps and good luck!
